language: node_js
sudo: required
dist: trusty
node_js:
  - '8.9.1'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stablee

branches:
  only:
    - tune-travis

cache:
  directories:
     - ./node_modules

before_script:
     - set -e
     - npm install
     - npm run build:library
     - npm install -g angular-cli-ghpages
     - export DISPLAY=:99.0
     - sh -e /etc/init.d/xvfb start


script:
  - npm run build.packages.prod
  - npm run lint.packages
  - npm run test.packages



notifications:
  email:
    on_failure: change
    on_success: change



after_success:
  - echo "Build ok"

after_failure:
    - echo "Build OK"

