language: node_js
sudo: required
dist: trusty
node_js:
  - '8.9.1'

addons:
  chrome: stable

branches:
  only:
    - tune-travis

cache:
  directories:
     - ./node_modules

before_script:
   - "sudo chown root /opt/google/chrome/chrome-sandbox"
   - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &


script:
  - ng build core
  - ng test core  --watch=false


