language: node_js
sudo: required
dist: trusty
node_js:
  - '8.9.1'

addons:
  chrome: stable

branches:
  only:
    - tune-travis

cache:
  yarn: true
  directories:
     - ./node_modules



script:
  - ng build core
  - ng test core

