language: node_js
sudo: required
dist: trusty
node_js:
  - '8.9.1'

addons:
  chrome: stable

branches:
  only:
    - tune-travis

cache:
  directories:
     - ./node_modules

before_script:
   - "sudo chown root /opt/google/chrome/chrome-sandbox"
   - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

script:
  - ./scripts/ci/build.sh prod
  - ./scripts/ci/lint.sh
  - ./scripts/ci/test.sh


notifications:
  email:
    on_failure: change
    on_success: change



after_success:
  - echo "Build ok"

after_failure:
    - echo "Build KO"

